try:#PROBAR
    n1 = int(input("Dame un numero: "))

except Exception as e:
    print("Ocurrio un error")    

